---
- hosts: all
  become: true

  vars:
    sshd: ssh
    sshd_config: /etc/ssh/sshd_config

  handlers:
    - name: restart sshd
      service: name={{ sshd }} state=restarted

  tasks:
    - name: Upgrade all apt packages
      apt: upgrade=safe update_cache=yes force_apt_get=yes

    - name: Install apt packages
      apt:
        name: ['python3', 'python3-pip', 'htop', 'wget', 'curl', 'git', 'net-tools', 'tmux', 'vim', 'fish']
        state: latest
        update_cache: yes

    - name: Update hostname
      hostname:
        name: "{{ hostname }}"

    - name: Ensure group 'docker' exists
      group:
        name: docker
        state: present

    - name: Add 'ubuntu' user to docker group
      user: 
        name: ubuntu
        groups: docker
        state: present

    - name: Create user account
      user: 
        name: "{{ lookup('env', 'USER') }}"
        groups: "ubuntu,adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,netdev,lxd,microk8s"
        shell: /usr/bin/fish
        state: present

    - name: Change new user password
      user:
        user: "{{ lookup('env', 'USER') }}"
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"

    - name: Add identity key to authorized keys on host
      authorized_key: 
        user: "{{ lookup('env', 'USER') }}"
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      register: add_identity_key

    - name: Disable empty password login
      lineinfile:
        dest: "{{ sshd_config }}"
        regexp: '^#?PermitEmptyPasswords'
        line: 'PermitEmptyPasswords no'
      notify: restart sshd

    - name: Disable remote root login
      lineinfile:
        dest: "{{ sshd_config }}"
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: restart sshd

    - name: Disable password login
      lineinfile: 
        dest: "{{ sshd_config }}" 
        regexp: '^(#\s*)?PasswordAuthentication '
        line: 'PasswordAuthentication no'
      when: 
        - add_identity_key is succeeded 
        - not add_identity_key is skipped
      notify: restart sshd

    - name: Update cgroups settings
      lineinfile:
        dest: /boot/firmware/cmdline.txt
        regexp: '(^(?!.*cgroup_enable.*$)[^\"]+)[\n]'
        backrefs: yes
        line: '\1 cgroup_enable=memory cgroup_memory=1'
      register: cmdline

    - name: Reboot system
      reboot:
      when: cmdline.changed
